version: '3'
services:
  app:
    build: .  # This builds using your Dockerfile
    depends_on:
      - mongodb
    environment:
      - TOKEN_SECRET=cff8c43509cf688e99090dbebd3aae0ed06a6baf65fa1438e3fbb3326dc59e9d
      - GOOGLE_CLIENT_ID=your_google_id
      - GOOGLE_CLIENT_SECRET=your_google_secret
      - GITHUB_CLIENT_ID=your_github_id
      - GITHUB_CLIENT_SECRET=your_github_secret
    ports:
      - "8080:8080"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: