# src/main/resources/application.yml
spring:
  # Using Spring Boot 3.4.3
  application:
    name: user-auth-service
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userdb
      auto-index-creation: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

# Server configuration              
server:
  port: 8080
  servlet:
    context-path: /api

# Logging configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.example: DEBUG

# App custom properties
app:
  auth:
    tokenSecret: ${TOKEN_SECRET:cff8c43509cf688e99090dbebd3aae0ed06a6baf65fa1438e3fbb3326dc59e9d}
    tokenExpirationMsec: 864000000 # 10 days
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect